// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzdystnqpizcrdryaqdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6ZHlzdG5xcGl6Y3JkcnlhcWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Njg1NjcsImV4cCI6MjA1OTA0NDU2N30.AgWYphKv2lSLDeIBHk6uPm3-9-NkjWyxpB8hHGAZwBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);